# Generated by Django 6.0.7 on 2026-08-01 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food_category/')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='foods_image/')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('narx', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.food_category')),
            ],
        ),
    ]
