# Generated by Django 6.0.7 on 2026-08-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='narx',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
