# Generated by Django 6.0.7 on 2026-08-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_alter_food_narx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food_category',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
