# Generated by Django 6.0.7 on 2026-08-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0003_alter_food_info_alter_food_category_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='narx',
            field=models.FloatField(),
        ),
    ]
