# Generated by Django 6.0.7 on 2026-08-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('accepted', 'Qabul qilindi'), ('cooking', 'Tayyorlanmoqda'), ('ready', 'Tayyor'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=20),
        ),
    ]
